### ISSUE TITLE
Count, Pay rent

### ISSUE THREAD

**Issue by stigtsp** [dimsumlabs/dsl-accounts#8]
- [x] Move cash from postbox to petty-cash 
- [x] Count all cash in petty-cash box
- [ ] Pay RENT for November

**Comment by stigtsp** [comment]
@leviathanch Can you pay rent today or tomorrow? :)

**Comment by leviathanch** [comment]
Ok!

**Comment by stigtsp** [comment]
levi paid rent yesterday ($13370 for some reason?) so closing this ticket

**Comment by leviathanch** [comment]
It might be that I paid a special value back then in order to make it exactly be this value :-)

**Comment by adisbladis** [comment]
What does this even mean? You cant screw up accounting because you want it to say "leet"

**Comment by leviathanch** [comment]
Hi
> What does this even mean? You cant screw up accounting because you want it
> to say "leet"
Didn't screw up accounting. Just donated  back in October so much that the 
money we had went up 13370 because we were needing 14000.
I did not mess around with the recent accounting. (Look at the thread, it's 
very old)

**Comment by leviathanch** [comment]
Also git has commit logs so we can tell when someone trolls accounting for 
real... So there is no way someone can stay anonymous with GIT involved...

**Comment by adisbladis** [comment]
I'm sorry. I misunderstood @stigtsp as rental payment being 13370, not the balance ending up being 13370.
